/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.*;
import java.awt.event.WindowEvent;
import Clases.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author PianitoDead
 */
public class Fm_AgregarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Fm_Agregar
     */
    
    public Fm_AgregarUsuario() {
        initComponents();
        setSize(1050, 656);
        this.setLocationRelativeTo(null);        
    }
    
    public void close(){
        
        WindowEvent Cerrar = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(Cerrar);
    }    
    
    public void Habilitar (){
        Combo_Tipo_ID.setEnabled(true);
        Combo_Area_Trab.setEnabled(true);
        Combo_Cargo.setEnabled(true);
        Combo_Estado_Usuario.setEnabled(true);        
        txt_Tipo_ID.setEnabled(true);
        txt_Nombre.setEnabled(true);
        txt_ApellidoP.setEnabled(true);
        txt_ApellidoM.setEnabled(true);
        txt_Login.setEnabled(true);
        txt_Pass.setEnabled(true);
        txt_rePass.setEnabled(true);
        txt_Email.setEnabled(true);
    }    
    
    public void Inhabilitar (){
        Combo_Tipo_ID.setEnabled(false);
        Combo_Area_Trab.setEnabled(false);
        Combo_Cargo.setEnabled(false);
        Combo_Estado_Usuario.setEnabled(false);        
        txt_Tipo_ID.setEnabled(false);
        txt_Nombre.setEnabled(false);
        txt_ApellidoP.setEnabled(false);
        txt_ApellidoM.setEnabled(false);
        txt_Login.setEnabled(false);
        txt_Pass.setEnabled(false);
        txt_rePass.setEnabled(false);
        txt_Email.setEnabled(false);
            
        txt_Tipo_ID.setText("");
        txt_Nombre.setText("");
        txt_ApellidoP.setText("");
        txt_ApellidoM.setText("");
        txt_Login.setText("");
        txt_Pass.setText("");
        txt_rePass.setText("");
        txt_Email.setText("");
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_Agregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Combo_Area_Trab = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Login = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Combo_Estado_Usuario = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        Combo_Cargo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Pass = new javax.swing.JPasswordField();
        txt_rePass = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Combo_Tipo_ID = new javax.swing.JComboBox<>();
        txt_Tipo_ID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_ApellidoP = new javax.swing.JTextField();
        txt_ApellidoM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 575));
        setSize(new java.awt.Dimension(1050, 575));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));

        Btn_Agregar.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        Btn_Agregar.setContentAreaFilled(false);
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("Datos Personales:");

        Btn_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_customer_32px_1.png"))); // NOI18N
        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.setContentAreaFilled(false);
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Guardar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Globe_32px.png"))); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.setContentAreaFilled(false);
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.setContentAreaFilled(false);
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(238, 112, 82));
        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 112, 82));
        jLabel6.setText("Datos Trabajador:");

        jLabel18.setBackground(new java.awt.Color(238, 112, 82));
        jLabel18.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 112, 82));
        jLabel18.setText("Area:");

        Combo_Area_Trab.setBackground(new java.awt.Color(0, 0, 0));
        Combo_Area_Trab.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        Combo_Area_Trab.setMaximumRowCount(10);
        Combo_Area_Trab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Seleccione Area***", "Seguridad", "Dirección", "Administración", "UICPV", "Asesoria Legal", "Promoción y Participación Ciudadana", "Planificación y Presupuesto", "Soporte Técnico", "Contabilidad", "Control Patrimonial", "Recepción y Tramite", "Arqueología", "Abastecimiento", "Tesoreria", "Conservación", "Cooperación Tecnica", "RRHH", "Imagen Institucional", "Unidad Formuladora" }));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("Datos Usuario:");

        jLabel19.setBackground(new java.awt.Color(238, 112, 82));
        jLabel19.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 112, 82));
        jLabel19.setText("Codigo Usuario:");

        txt_Codigo.setEditable(false);
        txt_Codigo.setBackground(new java.awt.Color(51, 0, 51));
        txt_Codigo.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        txt_Codigo.setText("AUTO-GENERADO");

        jLabel20.setBackground(new java.awt.Color(238, 112, 82));
        jLabel20.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 112, 82));
        jLabel20.setText("Nombre de Usuario:");

        txt_Login.setBackground(new java.awt.Color(204, 204, 204));
        txt_Login.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N

        jLabel21.setBackground(new java.awt.Color(238, 112, 82));
        jLabel21.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 112, 82));
        jLabel21.setText("Estado:");

        Combo_Estado_Usuario.setBackground(new java.awt.Color(51, 0, 0));
        Combo_Estado_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Seleccione Estado***", "Activo", "Inactivo", "Inhabiitado" }));

        jLabel25.setBackground(new java.awt.Color(238, 112, 82));
        jLabel25.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(238, 112, 82));
        jLabel25.setText("Cargo:");

        Combo_Cargo.setBackground(new java.awt.Color(102, 0, 102));
        Combo_Cargo.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        Combo_Cargo.setMaximumRowCount(10);
        Combo_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Seleccione Cargo***", "Jefe de Administración", "Jefe de Abastecimiento", "Responsable RRHH", "Responsable Control Patrimonial", "Tesorero", "Responsable Contabilidad", "Responsable Soporte Tecnico", "Coordinador", "Recepción", "Director", "Responsable de Imagen  Institucional", "Analista", "Jefe de Planificación y Presup", "Responsable de Servicios", "Jefe de UICPV", "Asistente Administración", "Especialista de RRHH", "Asistente de Dirección" }));

        jLabel26.setBackground(new java.awt.Color(238, 112, 82));
        jLabel26.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(238, 112, 82));
        jLabel26.setText("Contraseña:");

        jLabel27.setBackground(new java.awt.Color(238, 112, 82));
        jLabel27.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(238, 112, 82));
        jLabel27.setText("Confirmar Contraseña:");

        jLabel28.setBackground(new java.awt.Color(238, 112, 82));
        jLabel28.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(238, 112, 82));
        jLabel28.setText("Correo Electronico:");

        txt_Email.setBackground(new java.awt.Color(51, 0, 51));
        txt_Email.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N

        txt_Pass.setBackground(new java.awt.Color(255, 51, 51));
        txt_Pass.setForeground(new java.awt.Color(0, 0, 0));
        txt_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PassActionPerformed(evt);
            }
        });

        txt_rePass.setBackground(new java.awt.Color(0, 0, 204));

        jLabel17.setBackground(new java.awt.Color(238, 112, 82));
        jLabel17.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setText("Tipo de Identidad:");

        jLabel16.setBackground(new java.awt.Color(238, 112, 82));
        jLabel16.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setText("Tipo de Identidad:");

        Combo_Tipo_ID.setBackground(new java.awt.Color(204, 0, 0));
        Combo_Tipo_ID.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        Combo_Tipo_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Seleccione un tipo de Documento***", "D.N.I.", "PASAPORTE", "R.U.C.", "Temporal" }));

        txt_Tipo_ID.setBackground(new java.awt.Color(0, 51, 102));
        txt_Tipo_ID.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        jLabel22.setBackground(new java.awt.Color(238, 112, 82));
        jLabel22.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 112, 82));
        jLabel22.setText("Nombre:");

        jLabel23.setBackground(new java.awt.Color(238, 112, 82));
        jLabel23.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(238, 112, 82));
        jLabel23.setText("Apellido Paterno:");

        jLabel24.setBackground(new java.awt.Color(238, 112, 82));
        jLabel24.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(238, 112, 82));
        jLabel24.setText("Apellido Materno:");

        txt_Nombre.setBackground(new java.awt.Color(0, 153, 0));
        txt_Nombre.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N

        txt_ApellidoP.setBackground(new java.awt.Color(51, 0, 51));

        txt_ApellidoM.setBackground(new java.awt.Color(204, 204, 0));
        txt_ApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel7)
                                .addGap(469, 469, 469)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_Codigo)
                                            .addComponent(txt_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Btn_Nuevo)
                                                .addComponent(Combo_Estado_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(85, 85, 85)
                                        .addComponent(Btn_Guardar)))
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_Cancelar)
                                    .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Combo_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_rePass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Combo_Tipo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Combo_Area_Trab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Tipo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(244, 244, 244)))
                                .addGap(181, 181, 181)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(9, 9, 9))))
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_ApellidoP)
                            .addComponent(txt_Nombre))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Tipo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_Tipo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txt_ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_ApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Combo_Area_Trab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(32, 32, 32)))
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txt_rePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Combo_Estado_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Nuevo)
                    .addComponent(Btn_Guardar)
                    .addComponent(Btn_Cancelar))
                .addGap(58, 58, 58))
        );

        Btn_Nuevo.getAccessibleContext().setAccessibleDescription("Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMActionPerformed

    private void txt_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PassActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        Inhabilitar();
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:
        if(txt_Tipo_ID.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el ID.");
            txt_Tipo_ID.requestFocus();
            return;
        }

        if(txt_Nombre.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el Nombre.");
            txt_Nombre.requestFocus();
            return;
        }

        if(txt_ApellidoP.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el Em@il.");
            txt_ApellidoP.requestFocus();
            return;
        }

        if(txt_ApellidoM.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el Telefono.");
            txt_ApellidoM.requestFocus();
            return;
        }

        if(txt_Login.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el UserName.");
            txt_Login.requestFocus();
            return;
        }

        if(txt_Pass.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar una Contraseña.");
            txt_Pass.requestFocus();
            return;
        }

        if(txt_rePass.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar quien le Registro.");
            txt_rePass.requestFocus();
            return;
        }
        
        if(txt_Email.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar quien le Registro.");
            txt_Email.requestFocus();
            return;
        }

        Usuarios User = new Usuarios ();
        User.setId_Usuario(Integer.parseInt(txt_Tipo_ID.getText()));
        User.setNombre(txt_Nombre.getText());
        User.setApellidoM(txt_ApellidoM.getText());
        User.setApellidoP(txt_ApellidoP.getText());
        User.setEmail(txt_Email.getText());
        User.setUsername(txt_Login.getText());
        User.setPassword(txt_Pass.getText());
        
        JOptionPane.showMessageDialog(rootPane, "Registro Exitoso.");

        String Cadena= "\nID: " + User.getId_Usuario() + "\nNombre: " + User.getNombre() +  "\nApellido Paterno: " + User.getApellidoP() + 
         "\nApellido Materno: " + User.getApellidoM() + "\nEm@il: " + User.getEmail() +
         "\nNombre de Usuario: " + User.getUsername();

        JOptionPane.showMessageDialog(rootPane, "Datos Guardados" + Cadena);

        Inhabilitar();
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        txt_Tipo_ID.requestFocus();
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
        // TODO add your handling code here:

        Fm_GestionarUsuario Fm_GestionarUsuario = new Fm_GestionarUsuario();
        Fm_GestionarUsuario.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fm_AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fm_AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fm_AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fm_AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fm_AgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JComboBox<String> Combo_Area_Trab;
    private javax.swing.JComboBox<String> Combo_Cargo;
    private javax.swing.JComboBox<String> Combo_Estado_Usuario;
    private javax.swing.JComboBox<String> Combo_Tipo_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_ApellidoM;
    private javax.swing.JTextField txt_ApellidoP;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Login;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_Tipo_ID;
    private javax.swing.JPasswordField txt_rePass;
    // End of variables declaration//GEN-END:variables
}