/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monic
 */
public class Fm_GestionarReporte extends javax.swing.JFrame {
    
    DefaultTableModel Modelo = new DefaultTableModel();

    /**
     * Creates new form Fm_GestionarReporte
     */
    public Fm_GestionarReporte() {
        initComponents();
        
        Modelo.addColumn("ID");
        Modelo.addColumn("Nombre");
        Modelo.addColumn("Telefono");
        Modelo.addColumn("Email");
        Modelo.addColumn("UserName");
        TablaReporte.setModel(Modelo);
        
        setSize(1050, 656);
        this.setLocationRelativeTo(null);  
    }

    public void close(){
        
        WindowEvent Cerrar = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(Cerrar);
    }
    
    void centrar_columnas(){
            DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
            modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
            TablaReporte.getColumnModel().getColumn(0).setCellRenderer(modelocentrar); 
            TablaReporte.getColumnModel().getColumn(1).setCellRenderer(modelocentrar); 
            TablaReporte.getColumnModel().getColumn(2).setCellRenderer(modelocentrar); 
            TablaReporte.getColumnModel().getColumn(3).setCellRenderer(modelocentrar); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_GestionarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReporte = new javax.swing.JTable();
        Btn_MostrarDatos = new javax.swing.JButton();
        Btn_AgregarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1050, 656));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 656));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Gestionar Reporte.");

        Btn_GestionarReporte.setBackground(new java.awt.Color(0, 0, 0));
        Btn_GestionarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apoyo-tecnico.png"))); // NOI18N
        Btn_GestionarReporte.setBorder(null);
        Btn_GestionarReporte.setContentAreaFilled(false);
        Btn_GestionarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GestionarReporteActionPerformed(evt);
            }
        });

        TablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaReporte);

        Btn_MostrarDatos.setBackground(new java.awt.Color(0, 0, 0));
        Btn_MostrarDatos.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Btn_MostrarDatos.setForeground(new java.awt.Color(0, 0, 102));
        Btn_MostrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Btn_MostrarDatos.setText("Mostrar Datos.");
        Btn_MostrarDatos.setBorderPainted(false);
        Btn_MostrarDatos.setContentAreaFilled(false);
        Btn_MostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MostrarDatosActionPerformed(evt);
            }
        });

        Btn_AgregarReporte.setBackground(new java.awt.Color(255, 255, 255));
        Btn_AgregarReporte.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Btn_AgregarReporte.setForeground(new java.awt.Color(255, 255, 255));
        Btn_AgregarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        Btn_AgregarReporte.setText("Agregar");
        Btn_AgregarReporte.setContentAreaFilled(false);
        Btn_AgregarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Btn_GestionarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_AgregarReporte)
                .addGap(117, 117, 117)
                .addComponent(Btn_MostrarDatos)
                .addGap(382, 382, 382))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_GestionarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_MostrarDatos)
                    .addComponent(Btn_AgregarReporte))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GestionarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GestionarReporteActionPerformed
        // TODO add your handling code here:
        
        Fm_Seguridad Fm_Seguridad = new Fm_Seguridad();
        Fm_Seguridad.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_GestionarReporteActionPerformed

    private void Btn_MostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MostrarDatosActionPerformed
        // TODO add your handling code here:
        
        try {
            
        Vector datos = new Vector();         
        datos.add(Integer.toString(Modelo.getId_Usuario()));
        datos.add(User.getNombre());
        datos.add(User.getTelefono()); 
        datos.add(User.getEmail());
        datos.add(User.getUsername());
        Modelo.addRow(datos);             
        TablaTramite.setModel(Modelo);
            centrar_columnas();   
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_Btn_MostrarDatosActionPerformed

    private void Btn_AgregarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarReporteActionPerformed
        // TODO add your handling code here:
        
        Fm_AgregarReporte Fm_AgregarReporte = new Fm_AgregarReporte();
        Fm_AgregarReporte.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_AgregarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fm_GestionarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fm_GestionarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fm_GestionarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fm_GestionarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fm_GestionarReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AgregarReporte;
    private javax.swing.JButton Btn_GestionarReporte;
    private javax.swing.JButton Btn_MostrarDatos;
    private javax.swing.JTable TablaReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
