/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
//import AppPackage.AnimationClass;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.*;


/**
 *
 * @author monic
 */
public class Fm_Seguridad extends javax.swing.JFrame implements Runnable{
    
    String Hora,Minutos,Segundos;
    Thread Hilo;
    
    /**
     * Creates new form form_Seguridad
     */
    public Fm_Seguridad() {
        initComponents();
        txt_Fecha.setText(FechaActual());
        Hilo = new Thread(this);
        Hilo.start();
        setVisible(true);
    }
    
    public void Hora (){
        Calendar Calendario = new GregorianCalendar();
        Date Hora_Actual =  new Date();
        Calendario.setTime(Hora_Actual);
        Hora = Calendario.get(Calendar.HOUR_OF_DAY)>9?"" + Calendario.get(Calendar.HOUR_OF_DAY):"0" + Calendario.get(Calendar.HOUR_OF_DAY);
        Minutos = Calendario.get(Calendar.MINUTE)>9?"" + Calendario.get(Calendar.MINUTE):"0" + Calendario.get(Calendar.MINUTE);
        Segundos = Calendario.get(Calendar.SECOND)>9?"" + Calendario.get(Calendar.SECOND):"0" + Calendario.get(Calendar.SECOND);
        
    }
    
    public void run(){
        
        Thread current = Thread.currentThread();
        
        while (current == Hilo){
            Hora();
            txt_Hora.setText(Hora + ":" + Minutos + ":" + Segundos);                    
        }
    
    }
    public void close(){
        
        WindowEvent Cerrar = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(Cerrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Wallpaper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Btn_Ges_Usuario = new javax.swing.JButton();
        Btn_Ges_Tramite = new javax.swing.JButton();
        Btn_Ges_Reporte = new javax.swing.JButton();
        Btn_Ges_Roles = new javax.swing.JButton();
        Btn_Seguridad = new javax.swing.JButton();
        txt_Hora = new javax.swing.JLabel();
        txt_Fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel_Wallpaper.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Seguridad:");

        jLabel4.setBackground(new java.awt.Color(238, 112, 82));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 112, 82));
        jLabel4.setText("Gestionar Tramite.");

        jLabel6.setBackground(new java.awt.Color(238, 112, 82));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 112, 82));
        jLabel6.setText("Gestionar Usuario.");

        jLabel12.setBackground(new java.awt.Color(238, 112, 82));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 112, 82));
        jLabel12.setText("Gestionar Reporte.");

        jLabel14.setBackground(new java.awt.Color(238, 112, 82));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 112, 82));
        jLabel14.setText("Gestionar Roles.");

        Btn_Ges_Usuario.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        Btn_Ges_Usuario.setContentAreaFilled(false);
        Btn_Ges_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ges_UsuarioActionPerformed(evt);
            }
        });

        Btn_Ges_Tramite.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Tramite.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Tramite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Idea_96px.png"))); // NOI18N
        Btn_Ges_Tramite.setContentAreaFilled(false);
        Btn_Ges_Tramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ges_TramiteActionPerformed(evt);
            }
        });

        Btn_Ges_Reporte.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Reporte.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apoyo-tecnico.png"))); // NOI18N
        Btn_Ges_Reporte.setContentAreaFilled(false);
        Btn_Ges_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ges_ReporteActionPerformed(evt);
            }
        });

        Btn_Ges_Roles.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Roles.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Ges_Roles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Handshake_96px.png"))); // NOI18N
        Btn_Ges_Roles.setContentAreaFilled(false);
        Btn_Ges_Roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ges_RolesActionPerformed(evt);
            }
        });

        Btn_Seguridad.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Seguridad.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Seguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Today_96px.png"))); // NOI18N
        Btn_Seguridad.setContentAreaFilled(false);
        Btn_Seguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SeguridadActionPerformed(evt);
            }
        });

        txt_Hora.setBackground(new java.awt.Color(238, 112, 82));
        txt_Hora.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        txt_Hora.setForeground(new java.awt.Color(0, 255, 51));
        txt_Hora.setText("00:00:00");

        txt_Fecha.setBackground(new java.awt.Color(238, 112, 82));
        txt_Fecha.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        txt_Fecha.setForeground(new java.awt.Color(0, 255, 51));
        txt_Fecha.setText("DD/MM/YYYY");

        javax.swing.GroupLayout jLabel_WallpaperLayout = new javax.swing.GroupLayout(jLabel_Wallpaper);
        jLabel_Wallpaper.setLayout(jLabel_WallpaperLayout);
        jLabel_WallpaperLayout.setHorizontalGroup(
            jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Btn_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txt_Fecha)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                        .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(Btn_Ges_Usuario)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabel_WallpaperLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21)))
                        .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Btn_Ges_Tramite)
                                .addGap(35, 35, 35)
                                .addComponent(Btn_Ges_Roles)
                                .addGap(21, 21, 21))
                            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)))
                        .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Hora)
                                    .addComponent(Btn_Ges_Reporte))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabel_WallpaperLayout.setVerticalGroup(
            jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel_WallpaperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_Fecha)
                        .addComponent(txt_Hora))
                    .addComponent(Btn_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Ges_Tramite)
                    .addComponent(Btn_Ges_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ges_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ges_Roles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jLabel_WallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jLabel14)))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Wallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SeguridadActionPerformed
        // TODO add your handling code here:

        Fm_Login Fm_Login = new Fm_Login();
        Fm_Login.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_SeguridadActionPerformed

    private void Btn_Ges_RolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ges_RolesActionPerformed
        // TODO add your handling code here:

        Fm_AgregarRoles Fm_Roles = new Fm_AgregarRoles();
        Fm_Roles.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_Ges_RolesActionPerformed

    private void Btn_Ges_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ges_ReporteActionPerformed
        // TODO add your handling code here:

        Fm_GestionarReporte Fm_GestionarReporte = new Fm_GestionarReporte();
        Fm_GestionarReporte.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_Ges_ReporteActionPerformed

    private void Btn_Ges_TramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ges_TramiteActionPerformed
        // TODO add your handling code here:

        Fm_GestionarTramite Fm_GestionarTramite = new Fm_GestionarTramite();
        Fm_GestionarTramite.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_Ges_TramiteActionPerformed

    private void Btn_Ges_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ges_UsuarioActionPerformed
        // TODO add your handling code here:

        Fm_GestionarUsuario Fm_GestionarUsuario = new Fm_GestionarUsuario();
        Fm_GestionarUsuario.setVisible(true);
        close();
    }//GEN-LAST:event_Btn_Ges_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static String FechaActual(){
    
    Date Fecha=new Date();
    SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
    
    return formatoFecha.format(Fecha);
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fm_Seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fm_Seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fm_Seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fm_Seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fm_Seguridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ges_Reporte;
    private javax.swing.JButton Btn_Ges_Roles;
    private javax.swing.JButton Btn_Ges_Tramite;
    private javax.swing.JButton Btn_Ges_Usuario;
    private javax.swing.JButton Btn_Seguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jLabel_Wallpaper;
    private javax.swing.JLabel txt_Fecha;
    private javax.swing.JLabel txt_Hora;
    // End of variables declaration//GEN-END:variables
}
