/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author YolandaChunga
 */
public class Licencia extends javax.swing.JFrame {

    /**
     * Creates new form Licencia
     */
    public Licencia() {
        initComponents();
        setSize(700, 400);
        setResizable(false);
        setTitle("Licencia de uso");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono= new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TerminoyC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_TerminosyCond = new javax.swing.JTextArea();
        jCheckBox_Acepto = new javax.swing.JCheckBox();
        jButton_Continuar = new javax.swing.JButton();
        jButton_NoAcepto = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TerminoyC.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel_TerminoyC.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TerminoyC.setText("Terminos y Condiciones");
        getContentPane().add(jLabel_TerminoyC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jTextArea_TerminosyCond.setColumns(20);
        jTextArea_TerminosyCond.setRows(5);
        jScrollPane1.setViewportView(jTextArea_TerminosyCond);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 58, 600, 180));

        jCheckBox_Acepto.setText("Yo Acepto");
        jCheckBox_Acepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_AceptoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_Acepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButton_Continuar.setText("Continuar");
        jButton_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jButton_NoAcepto.setText("No Acepto");
        jButton_NoAcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NoAceptoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_NoAcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ContinuarActionPerformed
        //jButton_Continuar.addActionListener(jButton_Continuar.getAction());
        jButton_Continuar.setEnabled(false);
        //jCheckBox_Acepto.addActionListener(jButton_Continuar.getAction().getClass());
       // jButton_Continuar.getModel();
    }//GEN-LAST:event_jButton_ContinuarActionPerformed

    private void jButton_NoAceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NoAceptoActionPerformed
        //jButton_NoAcepto.addActionListener(jButton_NoAcepto.getAction());
        jButton_NoAcepto.setEnabled(true);
    }//GEN-LAST:event_jButton_NoAceptoActionPerformed

    private void jCheckBox_AceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_AceptoActionPerformed
        jCheckBox_Acepto.action(null, jButton_NoAcepto);
        jCheckBox_Acepto.action(null, jButton_Continuar);
        
       
//jCheckBox_Acepto.addChangeListener();
    }//GEN-LAST:event_jCheckBox_AceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Licencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Continuar;
    private javax.swing.JButton jButton_NoAcepto;
    private javax.swing.JCheckBox jCheckBox_Acepto;
    private javax.swing.JLabel jLabel_TerminoyC;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_TerminosyCond;
    // End of variables declaration//GEN-END:variables
}
